<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LocalMovies.Infrastructure\LocalMovies.Infrastructure.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>
</Project>