<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\MovieStudio.Application\MovieStudio.Application.csproj"/>
    <ProjectReference Include="..\..\..\Shared\MovieStudio.Domain\MovieStudio.Domain.csproj"/>
    <ProjectReference Include="..\LocalMovies.Infrastructure\LocalMovies.Infrastructure.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>