<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="LiteDB" />
        <PackageReference Include="CSVHelper" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="../../../Shared/MovieStudio.Domain/MovieStudio.Domain.csproj" />
    </ItemGroup>
</Project>