<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MediatR" Version="14.0.0"/>
    <PackageVersion Include="FluentValidation" Version="12.1.1"/>
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1"/>
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.0"/>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="LiteDB" Version="5.0.21"/>
    <PackageVersion Include="CSVHelper" Version="33.1.0"/>
  </ItemGroup>
</Project>